package model.Views.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Nov 18 18:07:07 AST 2014
// ---------------------------------------------------------------------
public interface EmployeesVo extends ViewObject {
    void setdeptIdVar(Integer value);
}

